apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zero-downtime-demo.fullname" . }}
  labels:
    {{- include "zero-downtime-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "zero-downtime-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zero-downtime-demo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: node:14.8.0-alpine3.11
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
